# Generated by Django 5.0.4 on 2024-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_categoria_remove_producto_nombre_producto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
