# Generated by Django 5.0.4 on 2024-04-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
