# Generated by Django 5.0.4 on 2024-05-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='null', upload_to='products', verbose_name='Imagen'),
        ),
    ]
